- id: '1575430027910'
  alias: Holiday Lights
  description: ''
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.garage_switch
    service: switch.turn_on
  - data:
      entity_id: switch.porch_switch
    service: switch.turn_on
  - data:
      message: Holiday Lights Turned On!
    service: notify.mobile_app_rich_s_iphone