## Automation

  - id: wakeup
    alias: Wakeup
    hide_entity: false
    trigger:
      platform: time
      at: "07:15:00"
    condition:
      - condition: state
        entity_id: input_boolean.morning_alarm
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
    - service: light.turn_on
      entity_id: group.bedroom_lamps
      data:
        brightness: 1
    - service: light.turn_on
      entity_id: group.bedroom_lamps
      data:
        transition: 900
        brightness: 255

  - id: turn_on_downstairs_morning_weekdays
    alias: Turn On Downstairs Morning Weekdays
    hide_entity: false
    trigger:
      platform: time
      at: "06:35:00"
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: or
          conditions:
            - condition: state
              entity_id: 'device_tracker.rich_iphone'
              state: 'home'
            - condition: template
              value_template: "{% if is_state_attr('climate.downstairs_nest', 'away_mode', 'off') %}true{% endif %}"
    action:
    - service: scene.turn_on
      entity_id: scene.bright_downstairs

  - id: turn_off_downstairs_morning_weekdays
    alias: Turn Off Downstairs Morning Weekdays
    hide_entity: false
    trigger:
      platform: time
      at: "08:15:00"
    condition:
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
    action:
    - service: light.turn_off
      entity_id: group.downstairs_lights
    - service: switch.turn_off
      entity_id: group.downstairs_lights

  - id: turn_on_downstairs_when_getting_dark
    alias: Turn On Downstairs When Getting Dark
    hide_entity: false
    trigger:
      platform: sun
      event: sunset
      offset: '-00:35:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.rich_iphone'
          state: 'home'
        - condition: template
          value_template: "{% if is_state_attr('climate.downstairs_nest', 'away_mode', 'off') %}true{% endif %}"
    action:
    - service: scene.turn_on
      entity_id: scene.bright_downstairs
    - service: notify.ios_rich_iphone
      data:
        message: "Downstairs lights turned on via automation"

  - id: turn_off_tv
    alias: Turn Off TV
    hide_entity: false
    trigger:
      platform: state
      entity_id: media_player.apple_tv_family_room
      to: 'off'
    condition:
      - condition: state
        entity_id: media_player.vizio_smartcast
        state: 'on'
    action:
    - service: media_player.turn_off
      entity_id: media_player.vizio_smartcast

  - id: turn_on_apple_tv
    alias: Turn On Apple TV
    hide_entity: false
    trigger:
      platform: state
      entity_id: media_player.vizio_smartcast
      to: 'on'
    condition:
      - condition: state
        entity_id: media_player.apple_tv_family_room
        state: 'off'
    action:
    - service: media_player.turn_on
      entity_id: media_player.apple_tv_family_room

  - id: turn_off_apple_tv
    alias: Turn Off Apple TV
    hide_entity: false
    trigger:
      platform: state
      entity_id: media_player.vizio_smartcast
      to: 'off'
    action:
    - service: media_player.turn_off
      entity_id: media_player.apple_tv_family_room

  - id: dinning_room_lighting_on
    alias: Dining Room Lighting On
    hide_entity: false
    trigger:
      platform: state
      entity_id: switch.dining_room_light_switch
      to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.dining_room

  - id: dinning_room_lighting_off
    alias: Dining Room Lighting Off
    hide_entity: false
    trigger:
      platform: state
      entity_id: switch.dining_room_light_switch
      to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.dining_room

  - id: arrive_home
    alias: Arrive Home
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.rich_iphone
        from: 'not_home'
        to: 'home'
    condition:
      - condition: state
        entity_id: switch.garage_light
        state: 'off'
    action:
    - service: switch.turn_on
      entity_id: switch.garage_light
    - service: script.timer_off_garage_light_timer

  - id: arrive_home_night
    alias: Arrive Home Night
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.rich_iphone
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: lock.front_door_lock_locked
        from: 'locked'
        to: 'unlocked'
      - platform: state
        entity_id: sensor.nest_home_away
        from: 'Away'
        to: 'Home'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:15:00"
        - condition: state
          entity_id: group.living_room_lamps
          state: 'off'
    action:
    - service: scene.turn_on
      entity_id: scene.dimmed_in_living_room

  - id: sync_unlock
    alias: Sync Unlock State
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_alarm_type
    condition:
      - condition: template
        value_template: '{{ is_state("sensor.front_door_lock_alarm_type", "19") or is_state("sensor.front_door_lock_alarm_type", "22")  }}'
    action:
      - service: lock.unlock
        entity_id: lock.front_door_lock_locked

  - id: sync_lock
    alias: Sync Lock State
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_alarm_type
    condition:
      - condition: state
        entity_id: 'sensor.front_door_lock_alarm_type'
        state: '21'
    action:
      - service: lock.lock
        entity_id: lock.front_door_lock_locked

  - id: nest_set_to_home
    alias: Nest Set to Home
    hide_entity: false
    trigger:
      platform: state
      entity_id: sensor.nest_home_away
      from: 'Away'
      to: 'Home'
    action:
    - service: notify.ios_rich_iphone
      data:
        message: "Nest Thermostat set to Home"

  - id: nest_set_to_away
    alias: Nest Set to Away
    hide_entity: false
    trigger:
      platform: state
      entity_id: sensor.nest_home_away
      from: 'Home'
      to: 'Away'
    action:
    - service: notify.ios_rich_iphone
      data:
        message: "Nest Thermostat set to Away"

  - id: ohm_connect_hour_active
    alias: OhmConnect Hour Active
    hide_entity: false
    trigger:
      platform: state
      entity_id: sensor.ohmconnect_status
      from: 'Inactive'
      to: 'Active'
    action:
    - service: notify.ios_rich_iphone
      data:
        message: "OhmHour started"

  - id: ohm_connect_hour_inactive
    alias: OhmConnect Hour Inactive
    hide_entity: false
    trigger:
      platform: state
      entity_id: sensor.ohmconnect_status
      from: 'Active'
      to: 'Inactive'
    action:
    - service: notify.ios_rich_iphone
      data:
        message: "OhmHour ended"

  - id: battery_low_alert_front_door_lock
    alias: Low Battery Alert - Front Door Lock
    trigger:
      platform: template
      value_template: '{{ states.sensor.battery_front_door_lock.state | int > 1 and states.sensor.battery_front_door_lock.state | int < 5 }}'
    action:
      - service: notify.ios_rich_iphone
        data_template:
          message: >
            Low Battery Alert - Front Door Lock is at {{ states.sensor.battery_front_door_lock.state }} %