- id: '157782425900'
  alias: Motion Detected
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_1_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_2_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.home_alerts
      state: 'on'
  action:
  - service: notify.ios_rich_iphone
    data:
      message: "Motion detected downstairs"

- id: '157782425901'
  alias: Door Unlocked
  hide_entity: false
  trigger:
    - platform: state
      entity_id: lock.front_door_lock_locked
      from: 'locked'
      to: 'unlocked'
  condition:
    - condition: state
      entity_id: input_boolean.home_alerts
      state: 'on'
  action:
  - service: notify.ios_rich_iphone
    data:
      message: "Front door unlocked"

- id: '157782425901'
  alias: Door Locked
  hide_entity: false
  trigger:
    - platform: state
      entity_id: lock.front_door_lock_locked
      from: 'unlocked'
      to: 'locked'
  condition:
    - condition: state
      entity_id: input_boolean.home_alerts
      state: 'on'
  action:
  - service: notify.ios_rich_iphone
    data:
      message: "Front door locked"

- id: '157782425904'
  alias: Left Garage Closed
  hide_entity: false
  trigger:
    - platform: state
      entity_id: cover.left_garage_door
      from: 'open'
      to: 'closed'
  condition:
    - condition: state
      entity_id: input_boolean.home_alerts
      state: 'on'
  action:
    - service: notify.ios_rich_iphone
      data:
        message: "Left Garage Door closed"

- id: '157782425905'
  alias: Right Garage Closed
  hide_entity: false
  trigger:
    - platform: state
      entity_id: cover.right_garage_door
      from: 'open'
      to: 'closed'
  condition:
    - condition: state
      entity_id: input_boolean.home_alerts
      state: 'on'
  action:
    - service: notify.ios_rich_iphone
      data:
        message: "Right Garage Door closed"

- id: '157782425906'
  alias: Left Garage Opened
  hide_entity: false
  trigger:
    - platform: state
      entity_id: cover.left_garage_door
      from: 'closed'
      to: 'open'
  condition:
    - condition: state
      entity_id: input_boolean.home_alerts
      state: 'on'
  action:
    - service: notify.ios_rich_iphone
      data:
        message: "Left Garage Door opened"

- id: '157782425907'
  alias: Right Garage Opened
  hide_entity: false
  trigger:
    - platform: state
      entity_id: cover.right_garage_door
      from: 'closed'
      to: 'open'
  condition:
    - condition: state
      entity_id: input_boolean.home_alerts
      state: 'on'
  action:
    - service: notify.ios_rich_iphone
      data:
        message: "Right Garage Door opened"

- id: '157782487200'
  alias: Arrive Home
  hide_entity: false
  trigger:
    - platform: state
      entity_id: device_tracker.rich_iphone
      from: 'not_home'
      to: 'home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_alerts

- id: '157782487201'
  alias: Dining Room Light Switch On
  hide_entity: false
  trigger:
    platform: state
    entity_id: switch.dining_room_light_switch
    to: 'on'
  condition:
    - condition: state
      entity_id: light.dining_room
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.dining_room

- id: '157782487202'
  alias: Dining Room Light Switch Off
  hide_entity: false
  trigger:
    platform: state
    entity_id: switch.dining_room_light_switch
    to: 'off'
  condition:
    - condition: state
      entity_id: light.dining_room
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.dining_room

- id: '157782487203'
  alias: Dining Room Lights On
  hide_entity: false
  trigger:
    platform: state
    entity_id: light.dining_room
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.dining_room_light_switch
        state: 'unavailable'
      - condition: state
        entity_id: switch.dining_room_light_switch
        state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.dining_room_light_switch

- id: '157782487204'
  alias: Sync Unlock State
  trigger:
    platform: state
    entity_id: sensor.front_door_lock_alarm_type
  condition:
    - condition: template
      value_template: '{{ is_state("sensor.front_door_lock_alarm_type", "19") or is_state("sensor.front_door_lock_alarm_type", "22")  }}'
  action:
    - service: lock.unlock
      entity_id: lock.front_door_lock_locked

- id: '157782487205'
  alias: Sync Lock State
  trigger:
    platform: state
    entity_id: sensor.front_door_lock_alarm_type
  condition:
    - condition: state
      entity_id: 'sensor.front_door_lock_alarm_type'
      state: '21'
  action:
    - service: lock.lock
      entity_id: lock.front_door_lock_locked

- id: '157782487206'
  alias: Low Battery Alert - Front Door Lock
  trigger:
    platform: template
    value_template: '{{ states.sensor.battery_front_door_lock.state | int > 1 and states.sensor.battery_front_door_lock.state | int < 5 }}'
  action:
    - service: notify.ios_rich_iphone
      data_template:
        message: >
          Low Battery Alert - Front Door Lock is at {{ states.sensor.battery_front_door_lock.state }} %

- id: '157782487207'
  alias: Garage Door Opened
  hide_entity: false
  trigger:
    - platform: state
      entity_id: cover.left_garage_door
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id: cover.right_garage_door
      from: 'closed'
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.garage_light
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.garage_light_timer

- id: '157782487208'
  alias: 'Start HomeKit'
  trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
      - platform: event
        event_type: zwave.network_complete_some_dead
  action:
    - service: homekit.start

- id: '157782519800'
  alias: Kitchen Light Switch On
  hide_entity: false
  trigger:
    platform: state
    entity_id: switch.kitchen_light_switch
    to: 'on'
  condition:
    - condition: state
      entity_id: light.kitchen
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kitchen

- id: '157782519801'
  alias: Kitchen Light Switch Off
  hide_entity: false
  trigger:
    platform: state
    entity_id: switch.kitchen_light_switch
    to: 'off'
  condition:
    - condition: state
      entity_id: light.kitchen
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kitchen

- id: '157782519802'
  alias: Kitchen Lights On
  hide_entity: false
  trigger:
    platform: state
    entity_id: light.kitchen
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.kitchen_light_switch
        state: 'unavailable'
      - condition: state
        entity_id: switch.kitchen_light_switch
        state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.kitchen_light_switch

- id: '157782519803'
  alias: Wakeup
  hide_entity: false
  trigger:
    platform: time
    at: "06:55:00"
  condition:
    - condition: state
      entity_id: input_boolean.morning_alarm
      state: 'on'
    - condition: state
      entity_id: light.bedroom
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: script.turn_on
    entity_id: script.wakeup_energize

- id: '157782519804'
  alias: Turn on downstains lights early morning
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_1_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_2_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_downstairs_motion
      state: 'off'
    - condition: state
      entity_id: group.downstairs_all_lights
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.downstairs_motion_detector_1_luminance
      below: '18'
    - condition: time
      after: '06:00:00'
      before: '8:00:00'
  action:
    - service: script.script_retry
      data:
        script_entity_id: script.bright_downstairs

- id: '157782519805'
  alias: Turn on downstains lights morning
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_1_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_2_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_downstairs_motion
      state: 'off'
    - condition: state
      entity_id: group.downstairs_all_lights
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.downstairs_motion_detector_1_luminance
      below: '18'
    - condition: time
      after: '08:00:00'
      before: '12:00:00'
  action:
    - service: script.script_retry
      data:
        script_entity_id: script.energize_downstairs

- id: '157782519806'
  alias: Turn on downstains lights afternoon
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_1_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_2_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_downstairs_motion
      state: 'off'
    - condition: state
      entity_id: group.downstairs_all_lights
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.downstairs_motion_detector_1_luminance
      below: '18'
    - condition: time
      after: '12:00:00'
      before: '19:00:00'
  action:
    - service: script.script_retry
      data:
        script_entity_id: script.concentrate_downstairs

- id: '157782519807'
  alias: Turn on downstains lights evening
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_1_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_2_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_downstairs_motion
      state: 'off'
    - condition: state
      entity_id: group.downstairs_all_lights
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.downstairs_motion_detector_1_luminance
      below: '18'
    - condition: time
      after: '19:00:00'
      before: '22:00:00'
  action:
    - service: script.script_retry
      data:
        script_entity_id: script.relax_downstairs

- id: '157782519808'
  alias: Turn on downstains lights night
  hide_entity: false
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_1_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_motion_detector_2_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_downstairs_motion
      state: 'off'
    - condition: state
      entity_id: group.downstairs_all_lights
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.downstairs_motion_detector_1_luminance
      below: '18'
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
  action:
    - service: script.script_retry
      data:
        script_entity_id: script.nightlight_downstairs

- id: '157782519809'
  alias: Turn off downstains lights
  trigger:
    - platform: time_pattern
      seconds: '/60'
  condition:
    - condition: state
      entity_id: group.downstairs_all_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.downstairs_motion_detector_1_sensor
      state: 'off'
      for:
        minutes: 30
    - condition: state
      entity_id: binary_sensor.downstairs_motion_detector_2_sensor
      state: 'off'
      for:
        minutes: 30
    - condition: state
      entity_id: input_boolean.disable_downstairs_motion
      state: 'off'
    - condition: state
      entity_id: media_player.vizio_smartcast
      state: 'off'
      for:
        minutes: 15
    - condition: time
      before: '19:00:00'
      after: '22:00:00'
  action:
    - service: script.turn_off_group_with_retry
      data:
        group_entity_id: group.downstairs_all_lights
    - service: notify.ios_rich_iphone
      data:
        message: "No motion for 30 minutes turning of downstairs lights"

- id: '157782519810'
  alias: 'last_motion_update'
  trigger:
    - platform: time_pattern
      seconds: '/30'
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.downstairs_last_motion
    - service: homeassistant.update_entity
      entity_id: sensor.downstairs_last_motion_1
    - service: homeassistant.update_entity
      entity_id: sensor.downstairs_last_motion_2

- id: '157782519811'
  alias: Low Battery Alert - Downstairs Motion Detector One
  trigger:
    - platform: template
      value_template: '{{ states.sensor.battery_downstairs_motion_detector_1.state | int > 1 and states.sensor.battery_downstairs_motion_detector_1.state | int < 5 }}'
  action:
    - service: notify.ios_rich_iphone
      data_template:
        message: >
          Low Battery Alert - Downstairs Motion Detector One is at {{ states.sensor.battery_downstairs_motion_detector_1.state }} %

- id: '157782519812'
  alias: Low Battery Alert - Downstairs Motion Detector Two
  trigger:
    - platform: template
      value_template: '{{ states.sensor.battery_downstairs_motion_detector_2.state | int > 1 and states.sensor.battery_downstairs_motion_detector_2.state | int < 5 }}'
  action:
    - service: notify.ios_rich_iphone
      data_template:
        message: >
          Low Battery Alert - Downstairs Motion Detector Two is at {{ states.sensor.battery_downstairs_motion_detector_1.state }} %

- id: '1575430027912'
  alias: Porch Light Switch On
  hide_entity: false
  trigger:
    platform: state
    entity_id: switch.porch_light_switch
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.porch

- id: '1575430027911'
  alias: Porch Light Switch Off
  hide_entity: false
  trigger:
    platform: state
    entity_id: switch.porch_light_switch
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.porch

- alias: Porch Lights On
  hide_entity: false
  trigger:
    platform: state
    entity_id: light.porch
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.porch_light_switch
        state: 'unavailable'
      - condition: state
        entity_id: switch.porch_light_switch
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.porch_light_switch

- id: '1575430027910'
  alias: Holiday Lights
  description: ''
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.garage_switch
    service: switch.turn_on
  - data:
      entity_id: switch.porch_switch
    service: switch.turn_on
  - data:
      message: Holiday Lights Turned On!
    service: notify.mobile_app_rich_s_iphone