## Automation

  - id: network_start
    alias: Check network on start
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: sensor.update_fastdotcom
      - delay: '00:01:00'
      - service: sensor.update_speedtest

  - id: wakeup
    alias: Wakeup
    hide_entity: true
    trigger:
      platform: time
      at: "06:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.morning_alarm
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
    - service: light.turn_on
      entity_id: group.bedroom_lamps
      data:
        brightness: 1
    - service: light.turn_on
      entity_id: group.bedroom_lamps
      data:
        transition: 900
        brightness: 255

  - id: turn_on_downstairs_morning_weekdays
    alias: Turn On Downstairs Morning Weekdays
    hide_entity: true
    trigger:
      platform: time
      at: "06:45:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
    - service: scene.turn_on
      entity_id: scene.good_morning

  - id: turn_off_upstairs_morning_weekdays
    alias: Turn Off Upstairs Morning Weekdays
    hide_entity: true
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
    - service: light.turn_off
      entity_id: group.bedroom_lamps

  - id: arrive_home
    alias: Arrive Home
    hide_entity: true
    trigger:
      platform: state
      entity_id: device_tracker.rich_iphone
      from: 'not_home'
      to: 'home'
    condition:
      - condition: state
        entity_id: switch.garage_light
        state: 'off'
    action:
    - service: switch.turn_on
      entity_id: switch.garage_light
    - service: script.timer_off_garage_light_timer

  - id: arrive_home_night
    alias: Arrive Home Night
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.rich_iphone
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: lock.front_door_lock_locked
        from: 'locked'
        to: 'unlocked'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:15:00"
        - condition: state
          entity_id: light.living_room_lamp
          state: 'off'
    action:
    - service: light.hue_activate_scene
      data:
        group_name: "Living Room"
        scene_name: "Dimmed"

  - id: sync_unlock
    alias: Sync Unlock State
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_alarm_type
    condition:
      - condition: template
        value_template: '{{ is_state("sensor.front_door_lock_alarm_type", "19") or is_state("sensor.front_door_lock_alarm_type", "22")  }}'
    action:
      - service: lock.unlock
        entity_id: lock.front_door_lock_locked

  - id: sync_lock
    alias: Sync Lock State
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_alarm_type
    condition:
        - condition: state
          entity_id: 'sensor.front_door_lock_alarm_type'
          state: '21'
    action:
      - service: lock.lock
        entity_id: lock.front_door_lock_locked

  - id: lock_door_using_scene
    alias: Lock Front Door Using Scene
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          service_data:
            entity_id: scene.going_to_bed
          domain: scene
          service: turn_on
      - platform: event
        event_type: call_service
        event_data:
          service_data:
            entity_id: scene.goodnight
          domain: scene
          service: turn_on
    action:
      - service: lock.lock
        entity_id: lock.front_door_lock_locked