## Automation

  - id: wakeup
    alias: Wakeup
    hide_entity: true
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.morning_alarm
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
    - service: light.turn_on
      entity_id: group.bedroom_lamps
      data:
        brightness: 1
    - service: light.turn_on
      entity_id: group.bedroom_lamps
      data:
        transition: 900
        brightness: 255

  - id: turn_on_downstairs_morning_weekdays
    alias: Turn On Downstairs Morning Weekdays
    hide_entity: true
    trigger:
      platform: time
      at: "06:30:00"
    condition:
      - condition: state
        entity_id: 'device_tracker.rich_iphone'
        state: 'home'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
    - service: scene.turn_on
      entity_id: scene.bright_downstairs

  - id: turn_on_downstairs_when_getting_dark
    alias: Turn On Downstairs When Getting Dark
    hide_entity: true
    trigger:
      platform: sun
      event: sunset
      offset: '-00:15:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.rich_iphone'
          state: 'home'
        - condition: template
          value_template: "{% if is_state_attr('climate.downstairs_nest', 'away_mode', 'off') %}true{% endif %}"
    action:
    - service: scene.turn_on
      entity_id: scene.bright_downstairs
    - service: notify.ios_rich_iphone
      data:
        message: "Downstairs lights turned on via automation"

  - id: dinning_room_lighting_on
    alias: Dining Room Lighting On
    hide_entity: true
    trigger:
      platform: state
      entity_id: switch.dining_room_light_switch
      to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.dining_room
      - service_template: >
          {% if is_state('sun.sun', 'below_horizon') and now().hour >= 19 %}
            script.relax_in_dining_room
          {% else %}
            script.bright_in_dining_room
          {% endif %}

  - id: dinning_room_lighting_off
    alias: Dining Room Lighting Off
    hide_entity: true
    trigger:
      platform: state
      entity_id: switch.dining_room_light_switch
      to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.dining_room

  - id: arrive_home
    alias: Arrive Home
    hide_entity: true
    trigger:
      platform: state
      entity_id: device_tracker.rich_iphone
      from: 'not_home'
      to: 'home'
    condition:
      - condition: state
        entity_id: switch.garage_light
        state: 'off'
    action:
    - service: switch.turn_on
      entity_id: switch.garage_light
    - service: script.timer_off_garage_light_timer

  - id: arrive_home_night
    alias: Arrive Home Night
    hide_entity: true
    trigger:
      - platform: state
        entity_id: device_tracker.rich_iphone
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: lock.front_door_lock_locked
        from: 'locked'
        to: 'unlocked'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:15:00"
        - condition: state
          entity_id: light.hue_foyer_lamp
          state: 'off'
    action:
    - service: light.hue_activate_scene
      data:
        group_name: "Foyer"
        scene_name: "Dimmed"

  - id: sync_unlock
    alias: Sync Unlock State
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_alarm_type
    condition:
      - condition: template
        value_template: '{{ is_state("sensor.front_door_lock_alarm_type", "19") or is_state("sensor.front_door_lock_alarm_type", "22")  }}'
    action:
      - service: lock.unlock
        entity_id: lock.front_door_lock_locked

  - id: sync_lock
    alias: Sync Lock State
    trigger:
      platform: state
      entity_id: sensor.front_door_lock_alarm_type
    condition:
        - condition: state
          entity_id: 'sensor.front_door_lock_alarm_type'
          state: '21'
    action:
      - service: lock.lock
        entity_id: lock.front_door_lock_locked

  - id: holiday_lights_on
    alias: Holiday Lights On
    hide_entity: true
    trigger:
      platform: sun
      event: sunset
      offset: "-00:15:00"
    action:
    - service: switch.turn_on
      entity_id: switch.porch_switch
    - service: script.christmas_in_porch
    - service: notify.ios_rich_iphone
      data:
        message: "Holiday lights turned on via automation"

  - id: holiday_lights_off
    alias: Holiday Lights Off
    hide_entity: true
    trigger:
      platform: time
      at: "21:25:00"
    action:
    - service: switch.turn_off
      entity_id: switch.porch_switch
    - service: light.turn_off
      entity_id: light.hue_porch_lamp_1
    - service: light.turn_off
      entity_id: light.hue_porch_lamp_2
    - service: notify.ios_rich_iphone
      data:
        message: "Holiday lights turned off via automation"