homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 562
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

automation: !include automations.yaml

automation old: !include_dir_merge_list automation

cloud: !include cloud.yaml

config:

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

discovery:
  ignore:
    - apple_tv
    - google_cast

frontend:
  javascript_version: latest

lovelace:

group: !include groups.yaml

history:

homekit: !include homekit.yaml

input_boolean: !include input_boolean.yaml

ios:

light: !include lights.yaml

logbook:
  exclude:
    entities:
      - automation.last_motion_update
      - sensor.downstairs_last_motion
      - sensor.downstairs_motion_detector_1
      - sensor.downstairs_motion_detector_1_sourcenodeid
      - sensor.downstairs_motion_detector_1_alarm_level
      - sensor.downstairs_motion_detector_1_alarm_type
      - sensor.downstairs_motion_detector_1_luminance
      - sensor.downstairs_last_motion_1
      - binary_sensor.downstairs_motion_1_detector_sensor
      - sensor.downstairs_motion_detector_2
      - sensor.downstairs_motion_detector_2_sourcenodeid
      - sensor.downstairs_motion_detector_2_alarm_level
      - sensor.downstairs_motion_detector_2_alarm_type
      - sensor.downstairs_motion_detector_2_luminance
      - sensor.downstairs_last_motion_2
      - binary_sensor.downstairs_motion_2_detector_sensor

logger:
  default: error

media_player: !include media_players.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

netatmo:
  api_key: !secret netatmo_api_client_id
  secret_key: !secret netatmo_api_client_secret
  username: !secret netatmo_api_username
  password: !secret netatmo_api_password

person:

python_script:

rachio:
  api_key: !secret rachio_api_key

recorder:
  purge_interval: 1
  purge_keep_days: 2
  exclude:
    entities:
      - automation.last_motion_update
      - sensor.downstairs_last_motion
      - sensor.downstairs_motion_detector_1
      - sensor.downstairs_motion_detector_1_sourcenodeid
      - sensor.downstairs_motion_detector_1_alarm_level
      - sensor.downstairs_motion_detector_1_alarm_type
      - sensor.downstairs_motion_detector_1_luminance
      - binary_sensor.downstairs_motion_1_detector_sensor
      - sensor.downstairs_motion_detector_2
      - sensor.downstairs_motion_detector_2_sourcenodeid
      - sensor.downstairs_motion_detector_2_alarm_level
      - sensor.downstairs_motion_detector_2_alarm_type
      - sensor.downstairs_motion_detector_2_luminance
      - binary_sensor.downstairs_motion_2_detector_sensor

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

sun:

system_health:

tplink:

updater:

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_username
    password: !secret roomba_password

wemo:

zone: !include zones.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret z_wave_network_key