homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 562
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

automation: !include automations.yaml

automation old: !include_dir_merge_list automation

cloud: !include cloud.yaml

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

default_config:

discovery:
  ignore:
    - apple_tv
    - google_cast

frontend:
  javascript_version: latest

lovelace:

group: !include groups.yaml

homekit: !include homekit.yaml

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true

input_boolean: !include input_boolean.yaml

logbook:
  exclude:
    domains:
      - zwave
      - automation
      - sensor
      - binary_sensor
      - light
      - group

logger:
  default: error

media_player: !include media_players.yaml

netatmo:
  api_key: !secret netatmo_api_client_id
  secret_key: !secret netatmo_api_client_secret
  username: !secret netatmo_api_username
  password: !secret netatmo_api_password

rachio:
  api_key: !secret rachio_api_key

recorder:
  purge_interval: 1
  purge_keep_days: 2
  exclude:
    domains:
      - zwave
      - automation
    entities:
      - sensor.downstairs_last_motion
      - sensor.downstairs_motion_detector_1
      - sensor.downstairs_motion_detector_1_sourcenodeid
      - sensor.downstairs_motion_detector_1_alarm_level
      - sensor.downstairs_motion_detector_1_alarm_type
      - sensor.downstairs_motion_detector_1_luminance
      - binary_sensor.downstairs_motion_1_detector_sensor
      - sensor.downstairs_motion_detector_2
      - sensor.downstairs_motion_detector_2_sourcenodeid
      - sensor.downstairs_motion_detector_2_alarm_level
      - sensor.downstairs_motion_detector_2_alarm_type
      - sensor.downstairs_motion_detector_2_luminance
      - binary_sensor.downstairs_motion_2_detector_sensor

script: !include scripts.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

tplink:

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_username
    password: !secret roomba_password
  
zone: !include zones.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret z_wave_network_key