homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 562
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

automation: !include automations.yaml

automation old: !include_dir_merge_list automation

cloud: !include cloud.yaml

config:

discovery:
  ignore:
    - apple_tv
    - google_cast

device_tracker:
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password

frontend:
  javascript_version: latest

lovelace:
  mode: yaml

group: !include groups.yaml

history:

homekit: !include homekit.yaml

http:
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret http_base_url

input_boolean: !include input_boolean.yaml

ios:

light: !include lights.yaml

logbook:
  exclude:
    entities:
      - automation.last_motion_update
      - sensor.downstairs_last_motion
      - sensor.downstairs_motion_detector_sourcenodeid
      - sensor.downstairs_motion_detector
      - sensor.downstairs_motion_detector_alarm_level
      - sensor.downstairs_motion_detector_alarm_type
      - binary_sensor.downstairs_motion_detector_sensor

logger:
  default: error

media_player: !include media_players.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

netatmo:
  api_key: !secret netatmo_api_client_id
  secret_key: !secret netatmo_api_client_secret
  username: !secret netatmo_api_username
  password: !secret netatmo_api_password

person:

python_script:

rachio:
  api_key: !secret rachio_api_key

recorder:
  purge_interval: 1
  purge_keep_days: 2

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

sun:

updater:

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_username
    password: !secret roomba_password

wemo:

zone: !include zones.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret z_wave_network_key