homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 562
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

frontend:
config:
updater:
discovery:
  ignore:
    - apple_tv
history:
logbook:
sun:

http:
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/lucasweb.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/lucasweb.duckdns.org/privkey.pem
  base_url: !secret http_base_url

logger:
  default: warn

ios:

zwave:
  usb_path: /dev/cu.usbmodem1411
  new_entity_ids: true
  network_key: !secret z_wave_network_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

light:
  platform: hue
  host: !secret hue_ip
  allow_hue_groups: true

#emulated_hue:
#  off_maps_to_on_domains:
#    - script
#    - scene
#  exposed_domains:
#    - scene
#    - input_boolean
#    - switch
#    - fan

ifttt:
  key: !secret ifttt_key

input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
zone: !include zones.yaml