homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 562
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

frontend:
  javascript_version: latest
config:
updater:
discovery:
  ignore:
    - apple_tv
    - google_cast
history:
logbook:
sun:

http:
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret http_base_url

logger:
  default: error

recorder:
  purge_interval: 2
  purge_keep_days: 7

ios:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret z_wave_network_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

mqtt:
  broker: localhost
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200

ifttt:
  key: !secret ifttt_key

apple_tv:
  - host: !secret apple_tv_1_ip
    login_id: !secret apple_tv_1_login
    name: Apple TV Family Room
    start_off: true
  - host: !secret apple_tv_2_ip
    login_id: !secret apple_tv_2_login
    name: Apple TV Bedroom
    start_off: true

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_username
    password: !secret roomba_password

cloud: !include cloud.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
zone: !include zones.yaml
light: !include lights.yaml
media_player: !include media_players.yaml