title: Home
views:
  - title: Overview
    id: overview
    cards:

      - type: vertical-stack
        cards:

          - type: entities
            entities:
              - entity: group.lights
                name: Lights
                icon: mdi:lightbulb
              - entity: group.all_fans
                name: Fans
                icon: mdi:fan
              - entity: media_player.vizio_smartcast
                name: TV
                icon: mdi:television

          - type: entities
            show_header_toggle: false
            entities:
            - sensor.home_presence_status
            - lock.front_door_lock_locked
            - sensor.downstairs_last_motion
            - input_boolean.home_alerts

          - type: entities
            entities:
              - person.rich

      - type: vertical-stack
        cards:
        - type: thermostat
          entity: climate.downstairs

        - type: glance
          title: Indoor
          show_name: false
          entities:
          - sensor.netatmo_downstairs_temperature
          - sensor.netatmo_downstairs_humidity
          - sensor.netatmo_downstairs_co2

        - type: glance
          title: Outdoor
          show_name: false
          entities:
          - sensor.netatmo_outdoor_temperature
          - sensor.netatmo_outdoor_humidity

  - title: Downstaris
    id: downstairs
    cards:

      - type: vertical-stack
        cards:

          - type: entities
            entities:
              - entity: group.downstairs_all_lights
                name: Lights
                icon: mdi:lightbulb
              - entity: group.downstairs_fans
                name: Fans
                icon: mdi:fan
              - entity: media_player.vizio_smartcast
                name: TV
                icon: mdi:television

          - type: entities
            entities:
              - sensor.netatmo_downstairs_temperature
              - sensor.netatmo_downstairs_noise
              - sensor.downstairs_motion_detector_luminance
              - sensor.downstairs_last_motion

          - type: entities
            entities:
            - scene.bright_downstairs
            - scene.energize_downstairs
            - scene.concentrate_downstairs
            - scene.relax_downstairs
            - scene.nightlight_downstairs
            - scene.tv_time

          - type: entities
            entities:
              - input_boolean.disable_downstairs_motion
              - vacuum.roomba

      - type: vertical-stack
        cards:

          - type: picture-glance
            title: Living Room
            image: /local/living-room.jpg
            entities:
              - light.living_room

          - type: entities
            entities:
              - light.living_room
              - entity: scene.bright_living_room
                name: Bright
              - entity: scene.dimmed_living_room
                name: Relax
              - entity: scene.nightlight_living_room
                name: Nightlight

          - type: picture-glance
            title: Family Room
            image: /local/family-room.jpg
            entities:
              - light.family_room
              - switch.family_room_light_switch
              - fan.family_room_fan_level

          - type: entities
            title: Family Room
            entities:
            - entity: light.family_room
              name: Lights
            - entity: switch.family_room_light_switch
              name: Fan Light Switch
            - entity: fan.family_room_fan_level
              name: Fan
            - entity: scene.bright_family_room
              name: Bright
            - entity: scene.energize_family_room
              name: Energize
            - entity: scene.concentrate_family_room
              name: Concentrate
            - entity: scene.relax_family_room
              name: Relax
            - entity: scene.nightlight_family_room
              name: Nightlight
            - entity: scene.purple_family_room
              name: Purple

          - type: picture-glance
            title: Dining Room
            image: /local/dining-room.jpg
            entities:
              - light.dining_room

          - type: entities
            entities:
              - entity: light.dining_room
                name: Lights
              - entity: scene.bright_dining_room
                name: Bright
              - entity: scene.energize_dining_room
                name: Energize
              - entity: scene.concentrate_dining_room
                name: Concentrate
              - entity: scene.relax_dining_room
                name: Relax
              - entity: scene.nightlight_dining_room
                name: Nightlight


          - type: entities
            title: Kitchen
            entities:
              - entity: light.kitchen
                name: Lights
              - entity: switch.kitchen_under_cabinet_light_switch
                name: Cabinet Lights Switch
              - entity: switch.kitchen_sink_light_switch
                name: Sink Light Switch
              - entity: scene.bright_kitchen
                name: Bright
              - entity: scene.energize_kitchen
                name: Energize
              - entity: scene.concentrate_kitchen
                name: Concentrate
              - entity: scene.relax_kitchen
                name: Relax
              - entity: scene.nightlight_kitchen
                name: Nightlight

  - title: Upstairs
    id: upstairs
    cards:

      - type: vertical-stack
        cards:

          - type: entities
            entities:
              - entity: group.upstairs_lights
                name: Lights
                icon: mdi:lightbulb
              - entity: group.upstairs_fans
                name: Fans
                icon: mdi:fan

          - type: entities
            entities:
              - scene.kids_bedtime
              - scene.kids_good_night
              - scene.bedtime
              - scene.good_night

      - type: vertical-stack
        cards:

          - type: entities
            title: Bedroom
            entities:
              - light.bedroom
              - fan.bedroom_fan_level
              - switch.bathroom_light_switch

          - type: entities
            entities:
              - input_boolean.morning_alarm

      - type: vertical-stack
        cards:

          - type: entities
            title: Kids Room
            entities:
              - switch.kids_room_light_switch
              - light.hue_kids_room_lamp
              - fan.kids_room_fan_level

          - type: entities
            title: Playroom
            entities:
              - switch.playroom_light_switch
              - fan.playroom_fan_level

  - title: Cameras
    id: cameras
    cards:

    - type: picture-glance
      title: Porch Camera
      camera_image: camera.porch
      entities:
      - binary_sensor.porch_camera_motion_detected
      - binary_sensor.porch_camera_person_detected
      - binary_sensor.porch_camera_sound_detected

  - title: Outside
    id: outside
    cards:

      - type: vertical-stack
        cards:

          - type: entities
            entities:
              - entity: group.outside_lights
                name: Lights
                icon: mdi:lightbulb

          - type: entities
            title: Sprinklers
            show_header_toggle: false
            entities:
              - binary_sensor.rachio_online
              - switch.rachio_in_standby_mode
              - switch.front_yard_lawn
              - switch.front_yard_shrubs
              - switch.back_yard_lawn
              - switch.back_yard_shrubs

      - type: vertical-stack
        cards:

          - type: entities
            title: Porch
            entities:
              - switch.porch_light_switch
              - light.porch
              - switch.porch_switch

          - type: entities
            title: Garage
            entities:
              - switch.garage_light
              - switch.garage_switch

          - type: entities
            title: Patio
            entities:
              - switch.patio_light_switch

  - title: Debug
    id: debug

    cards:

      - type: entities
        title: Network
        entities:
          - sensor.lucasweb_duckdns_org

      - type: entities
        title: Smoke Alarms
        entities:
          - binary_sensor.downstairs_nest_protect_online
          - binary_sensor.upstairs_nest_protect_online
          - binary_sensor.upstairs_nest_protect_2_online
          - binary_sensor.bedroom_nest_protect_online
          - binary_sensor.kids_room_nest_protect_online

      - type: entities
        title: Batteries
        entities:
          - sensor.battery_front_door_lock
          - sensor.battery_downstairs_motion_detector
          - sensor.battery_vacuum_roomba
